### ISSUE TITLE
Remove support for ConstraintName of VariableIndex constraints

### ISSUE THREAD

**Issue by dourouc05** [dourouc05/CPLEXCP.jl#3]
According to https://jump.dev/MathOptInterface.jl/stable/release_notes/#Breaking-changes-in-MOI: 

> VariableIndex constraints should not support ConstraintName

I think this implies that https://github.com/dourouc05/CPLEXCP.jl/blob/master/src/MOI/wrapper.jl#L42-L48 should go away, along with all their related code (https://github.com/dourouc05/CPLEXCP.jl/blob/a05526dcb09b60347197857dfa1c86b637b32b3d/src/MOI/wrapper_constraints_names.jl#L1-L106, in a crude approximation).

@odow is my understanding right? If so, this could simplify this wrapper by quite a bit.

**Comment by odow** [comment]
Yes. We got rid of this because it over-complicated all of the wrappers.

**Comment by dourouc05** [comment]
Thanks! Indeed, that's quite a simplification (136 lines deleted, only one code path for constraint names instead of a dozen).
